#!/bin/bash

set -e

echo "Download artifacts from github.com"

TOKEN=$1
REPO=$2
RUN_ID=$3

artifacts=$(curl -L \
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer ${TOKEN}" \
-H "X-GitHub-Api-Version: 2022-11-28" \
https://api.github.com/repos/${REPO}/actions/runs/${RUN_ID}/artifacts | jq -r ".artifacts[])

echo "Download from github"

for artifac in artifacts; do
echo "$artifact"
done

