
name: Delivery pipeline
run-name: ${{github.actor}} - pipeline
on:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  
  pipeline-delivery:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          npm install
      
      - name: Running Tests
        run: | 
          npm run test
      
      - name: Build Project
        run: | 
          npm run build
      
      - name: Zip Archive
        run: | 
          zip -r ${{github.run_id}} dist
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: food-app
          path: dist
      
      
      